<?php

namespace atc\WHx4\Modules\People\Fields;

use atc\WHx4\Core\Contracts\FieldGroupInterface;

final class PersonFields implements FieldGroupInterface
{
    public static function register(): void
    {
        if ( !function_exists('acf_add_local_field_group') ) return;

        acf_add_local_field_group( [
            'key' => 'group_whx4_person', //'key' => 'group_624775b57f8df',
            'title' => 'WHx4 Person: Additional Fields',
            'fields' => [
                [
                    'key' => 'field_whx4_person_basics_tab',
                    'label' => 'Person Basics',
                    'name' => 'person_basics_tab',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '22',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key' => 'field_whx4_624775c6b621b',
                    //'key' => 'field_whx4_person_first_name',
                    //'key' => 'field_624775c6b621b',
                    'label' => 'First Name',
                    'name' => 'first_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775d1b621c',
                    //'key'    =>    'field_whx4_person_middle_name',
                    //'key' => 'field_624775d1b621c',
                    'label' => 'Middle Name',
                    'name' => 'middle_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '22',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775dbb621d',
                    //'key'    =>    'field_whx4_person_last_name',
                    //'key' => 'field_624775dbb621d',
                    'label' => 'Last Name',
                    'name' => 'last_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775e3b621e',
                    //'key'    =>    'field_whx4_initials',
                    //'key' => 'field_624775e3b621e',
                    'label' => 'Initials',
                    'name' => 'initials',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '7',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775eab621f',
                    //'key'    =>    'field_whx4_person_prefix',
                    //'key' => 'field_624775eab621f',
                    'label' => 'Prefix',
                    'name' => 'prefix',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '10',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775eeb6220',
                    //'key'    =>    'field_whx4_person_suffix',
                    //'key' => 'field_624775eeb6220',
                    'label' => 'Suffix',
                    'name' => 'suffix',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '10',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775f4b6221',
                    //'key'    =>    'field_whx4_person_job_title',
                    //'key' => 'field_624775f4b6221',
                    'label' => 'Job Title',
                    'name' => 'job_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_624775f9b6222',
                    //'key'    =>    'field_whx4_person_website',
                    //'key' => 'field_624775f9b6222',
                    'label' => 'Website',
                    'name' => 'website',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key'    =>    'field_whx4_62477603b6223',
                    //'key'    =>    'field_whx4_person_email_address',
                    //'key' => 'field_62477603b6223',
                    'label' => 'Email Address',
                    'name' => 'email_address',
                    'aria-label' => '',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key'    =>    'field_whx4_6247760db6224',
                    //'key'    =>    'field_whx4_person_phone_number',
                    //'key' => 'field_6247760db6224',
                    'label' => 'Phone Number',
                    'name' => 'phone_number',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_6247761bb6225',
                    //'key'    =>    'field_whx4_person_birth_year',
                    //'key' => 'field_6247761bb6225',
                    'label' => 'Birth Year',
                    'name' => 'birth_year',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_62477625b6226',
                    //'key'    =>    'field_whx4_person_death_year',
                    //'key' => 'field_62477625b6226',
                    'label' => 'Death Year',
                    'name' => 'death_year',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_62477629b6227',
                    //'key'    =>    'field_whx4_person_dates',
                    //'key' => 'field_62477629b6227',
                    'label' => 'Dates',
                    'name' => 'dates',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key'    =>    'field_whx4_6247762db6228',
                    //'key'    =>    'field_whx4_person_user_account',
                    //'key' => 'field_6247762db6228',
                    'label' => 'User Account',
                    'name' => 'user_account',
                    'aria-label' => '',
                    'type' => 'user',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'role' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'array',
                    'bidirectional_target' => [],
                ],
                [
                    'key'    =>    'field_whx4_64876136e25a3',
                    //'key'    =>    'field_whx4_person_special_name',
                    //'key' => 'field_64876136e25a3',
                    'label' => 'Special Name',
                    'name' => 'special_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'This field is ONLY to be used in very special cases, i.e. "The Boss", or "The Rector". It will supersede all other name fields in event programs.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_whx4_person_ids',
                    'label' => 'Identities',
                    'name' => 'identities',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'post_type' => [
                        0 => 'identity',
                    ],
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 1,
                    'save_custom' => 1,
                    'save_post_type' => 'identity',
                    'save_post_status' => 'publish',
                    /*'acfe_bidirectional' => [
                        'acfe_bidirectional_enabled' => '1',
                        'acfe_bidirectional_related' => [
                            0 => 'field_whx4_identity_person',
                        ],
                    ],*/
                    'bidirectional' => 1,
                    'bidirectional_target' => [
                        0 => 'field_whx4_identity_person',
                    ],
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'ui' => 1,
                ],
                [
                    'key'    =>    'field_whx4_64b065e9a96c7',
                    //'key'    =>    'field_whx4_person_media_tab',
                    //'key' => 'field_64b065e9a96c7',
                    'label' => 'Media',
                    'name' => 'media_tab',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '22',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key'    =>    'field_whx4_64b06589b33da',
                    //'key'    =>    'field_whx4_person_image_gallery',
                    //'key' => 'field_64b06589b33da',
                    'label' => 'Image Gallery',
                    'name' => 'image_gallery',
                    'aria-label' => '',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'return_format' => 'id',
                    'library' => 'all',
                    'min' => '',
                    'max' => '',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'insert' => 'append',
                    'preview_size' => 'medium',
                ],
                [
                    'key'    =>    'field_whx4_64b065d2a96c6',
                    //'key'    =>    'field_whx4_person_notes_tab',
                    //'key' => 'field_64b065d2a96c6',
                    'label' => 'Notes',
                    'name' => 'notes_tab',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '22',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key'    =>    'field_whx4_6247763bb6229',
                    //'key'    =>    'field_whx4_person_notes',
                    //'key' => 'field_6247763bb6229',
                    'label' => 'Notes',
                    'name' => 'notes',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ],
                [
                    'key'    =>    'field_whx4_664c8a5fcb582',
                    //'key'    =>    'field_whx4_person_affiliations_tab',
                    //'key' => 'field_664c8a5fcb582',
                    'label' => 'Affiliations and Identities [DEPRECATED]',
                    //'label' => 'Titles and Affiliations',
                    'name' => 'affiliations_tab',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '22',
                        'class' => 'float-left',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key'    =>    'field_whx4_664c8a72cb583',
                    //'key'    =>    'field_whx4_person_affiliations',
                    //'key' => 'field_664c8a72cb583',
                    'label' => 'Affiliations',
                    'name' => 'affiliations',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'relevanssi_exclude' => 0,
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => [
                        [
                            'key'    =>    'field_whx4_664c8aa2cb585',
                            //'key'    =>    'field_whx4_person_affiliations_role',
                            //'key' => 'field_664c8aa2cb585',
                            'label' => 'Role',
                            'name' => 'role',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'relevanssi_exclude' => 0,
                            'taxonomy' => 'person_role',
                            'add_term' => 1,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'select',
                            'allow_null' => 1,
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'bidirectional_target' => [],
                            'parent_repeater' => 'field_whx4_664c8a72cb583',
                            //'parent_repeater' => 'field_whx4_person_affiliations',
                        ],
                        // TODO: decide whether separate 'title' field is useful
                        // Consider event-specific titles vs. group-affiliated titles -- might be e.g. Soprano with Musica Sacra but also Soprano Soloist with Sacra for a specific concert...
                        /*[
                            'key'    =>    'field_whx4_affiliations_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'relevanssi_exclude' => 0,
                            'taxonomy' => 'person_title',
                            'add_term' => 1,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'select',
                            'allow_null' => 1,
                            'bidirectional' => 0,
                            'multiple' => 0,
                            'bidirectional_target' => [],
                            'parent_repeater' => 'field_whx4_affiliations',
                        ],*/
                        [
                            'key'    =>    'field_whx4_664c8a86cb584',
                            //'key'    =>    'field_whx4_affiliations_group',
                            //'key' => 'field_664c8a86cb584',
                            'label' => 'Group', // TODO: add option to designate "At large" if title relates to no specific group/org
                            'name' => 'group',
                            'aria-label' => '',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => [
                                [
                                    [
                                        'field' => 'field_whx4_at_large',
                                        'operator' => '==',
                                        'value' => '0',
                                    ],
                                ],
                            ],
                            'wrapper' => [
                                'width' => '40',
                                'class' => '',
                                'id' => '',
                            ],
                            'relevanssi_exclude' => 0,
                            'post_type' => [
                                0 => 'group',
                            ],
                            'post_status' => '',
                            'taxonomy' => '',
                            'return_format' => 'id',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional' => 0,
                            'ui' => 1,
                            'bidirectional_target' => [],
                            'parent_repeater' => 'field_whx4_affiliations',
                        ],
                        [
                            'key'    =>    'field_whx4_664c8bd2f2841',
                            //'key'    =>    'field_whx4_affiliations_dates',
                            //'key' => 'field_664c8bd2f2841',
                            'label' => 'Dates',
                            'name' => 'dates',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => 'Dates of affiliation/activity',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                            'relevanssi_exclude' => 0,
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_whx4_affiliations',
                        ],
                        [
                            'key' => 'field_whx4_at_large',
                            'label' => 'At Large',
                            'name' => 'at_large',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => 'Preferred general title', //'Check this box if this is the person\'s preferred general title, not in affiliation with any specific group',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '10',
                                'class' => '',
                                'id' => '',
                            ],
                            'relevanssi_exclude' => 0,
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                            'parent_repeater' => 'field_whx4_affiliations',
                        ],
                        [
                            'key' => 'field_whx4_current_role',
                            'label' => 'Current Role?',
                            'name' => 'current_role',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '10',
                                'class' => '',
                                'id' => '',
                            ],
                            'relevanssi_exclude' => 0,
                            'message' => '',
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                            'parent_repeater' => 'field_whx4_affiliations',
                        ],
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'person',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ] );
    }
}
