<?php

namespace atc\WHx4\Modules\Projects\Fields;

use atc\WHx4\Core\Contracts\FieldGroupInterface;

// TODO: rename all fields (keys/names) according to whx4 naming conventions
final class ProjectFields implements FieldGroupInterface
{
    public static function register(): void
    {
        //error_log( '=== XXXFields: register()) ===' );
        if ( !function_exists('acf_add_local_field_group') ) return;

        //use atc\WHx4\Migrations\FieldKeyMigrator;
        /*
        // Migrate
        FieldKeyMigrator::migrate([
            'field_624775f4b6221' => [
                'new_field_key' => 'field_whx4_modulename_first_name',
                'old_meta_key'  => 'first_name',
                'new_meta_key'  => 'whx4_modulename_first_name',
            ],
            'field_abc123xyz456' => [
                'new_field_key' => 'field_whx4_notes',
                // no meta_key rename
            ],
        ]);
        */

        acf_add_local_field_group( array(
            'key' => 'group_640f39f894735',
            'title' => 'Project Details',
            'fields' => array(
                array(
                    'key' => 'field_640f3b5a0784f',
                    'label' => 'Procedures & Logistics',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_640f39f95a9e1',
                    'label' => 'Logistics',
                    'name' => 'logistics',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'field_640f3ef3e3471',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_640f3ef3e3471',
                            'label' => 'Info Label (TXT/TMP)',
                            'name' => 'info_label_txt',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_640f39f95a9e1',
                        ),
                        array(
                            'key' => 'field_640f3e9fb271b',
                            'label' => 'Info Content',
                            'name' => 'info_content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                            'parent_repeater' => 'field_640f39f95a9e1',
                        ),
                        array(
                            'key' => 'field_642edb44cba74',
                            'label' => 'Documents (TMP)',
                            'name' => 'documents_tmp',
                            'aria-label' => '',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'parent_repeater' => 'field_640f39f95a9e1',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_640f3b995a09d',
                    'label' => 'Schedule/Events',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_640f3a5b83d85',
                    'label' => 'Rehearsal Schedule',
                    'name' => 'rehearsal_schedule',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_640f3aec32f45',
                    'label' => 'Project Events',
                    'name' => 'projects_events',
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'post_type' => array(
                        0 => 'event',
                    ),
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'post_type',
                        2 => 'taxonomy',
                    ),
                    'return_format' => 'object',
                    'min' => '',
                    'max' => '',
                    'elements' => '',
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_640f3b38a33ee',
                    'label' => 'Personnel',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_640f46c99ad9f',
                    'label' => 'Project Personnel',
                    'name' => 'project_personnel',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'field_640f3ef3e3471',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_640f46c99ada0',
                            'label' => 'Person Label (TXT/TMP)',
                            'name' => 'person_label_txt',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '15',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_640f46c99ad9f',
                        ),
                        array(
                            'key' => 'field_640f46c99ada1',
                            'label' => 'Person',
                            'name' => 'person',
                            'aria-label' => '',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'post_type' => array(
                                0 => 'person',
                            ),
                            'taxonomy' => '',
                            'return_format' => 'object',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 1,
                            'bidirectional_target' => array(
                            ),
                            'parent_repeater' => 'field_640f46c99ad9f',
                        ),
                        array(
                            'key' => 'field_64148af94722f',
                            'label' => 'Organization',
                            'name' => 'project_group',
                            'aria-label' => '',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'group',
                            ),
                            'post_status' => '',
                            'taxonomy' => '',
                            'return_format' => 'object',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'bidirectional' => 0,
                            'ui' => 1,
                            'bidirectional_target' => array(
                            ),
                            'parent_repeater' => 'field_640f46c99ad9f',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_640f3dde654d4',
                    'label' => 'Links and Files',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_640f3df0654d5',
                    'label' => 'Links',
                    'name' => 'links',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'field_64148c6da2b29',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_64148c6da2b29',
                            'label' => 'URL (TMP)',
                            'name' => 'url',
                            'aria-label' => '',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_640f3e21654d6',
                                        'operator' => '==empty',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'parent_repeater' => 'field_640f3df0654d5',
                        ),
                        array(
                            'key' => 'field_64148c99a2b2a',
                            'label' => 'Link Title (TMP)',
                            'name' => 'link_title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_640f3e21654d6',
                                        'operator' => '==empty',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_640f3df0654d5',
                        ),
                        array(
                            'key' => 'field_640f3e21654d6',
                            'label' => 'Link',
                            'name' => 'link',
                            'aria-label' => '',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_64148c6da2b29',
                                        'operator' => '==empty',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'readonly' => 0,
                            'post_type' => array(
                                0 => 'link',
                            ),
                            'taxonomy' => '',
                            'return_format' => 'object',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 1,
                            'bidirectional_target' => array(
                            ),
                            'parent_repeater' => 'field_640f3df0654d5',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6414efc79ed99',
                    'label' => 'Logbook',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_64150dfbebf89',
                    'label' => 'Log Entries',
                    'name' => 'posts_projects',
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'post',
                    ),
                    'post_status' => '',
                    'taxonomy' => array(
                        0 => 'category:log-entries',
                    ),
                    'filters' => array(
                        0 => 'search',
                    ),
                    'return_format' => 'object',
                    'min' => '',
                    'max' => '',
                    'elements' => '',
                    'bidirectional' => 0,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_6489c64e6df1b',
                    'label' => 'Files',
                    'name' => 'files',
                    'aria-label' => '',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'return_format' => 'array',
                    'library' => 'all',
                    'min' => '',
                    'max' => '',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'insert' => 'append',
                    'preview_size' => 'medium',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'project',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
            ) );
    }
}
