<?php

namespace atc\WHx4\Modules\Snippets\Fields;

use atc\WXC\Contracts\FieldGroupInterface;

final class SnippetFields implements FieldGroupInterface
{
    public static function register(): void
    {
        if ( !function_exists('acf_add_local_field_group') ) return;

        acf_add_local_field_group( array(
			'key' => 'group_651dab1c9a033',
			'title' => 'Snippet Logic',
			'fields' => array(
				array(
					'key' => 'field_651ef6d23b1aa',
					'label' => 'Show/Hide',
					'name' => 'snippet_display',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'highlight-green',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'show' => 'Show everywhere',
						'hide' => 'Hide everywhere',
						'selected' => 'Show widget on selected',
						'notselected' => 'Hide widget on selected',
						'conditional' => 'Show conditionally (TMP)',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6556cd3fcf40a',
					'label' => 'Priority',
					'name' => 'snippet_priority',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						3 => 'Low',
						2 => 'Standard',
						1 => 'High',
					),
					'default_value' => 2,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_65286c51bfaa6',
					'label' => 'Any/All?',
					'name' => 'any_all',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '!=',
								'value' => 'show',
							),
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '!=',
								'value' => 'hide',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => 'checklist',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'any' => 'Match ANY of the conditions',
						'all' => 'Match ALL of the conditions',
					),
					'default_value' => 'any',
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'horizontal',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_65de1695ef9e2',
					'label' => 'Snippet Position',
					'name' => 'snippet_position',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'side' => 'Side',
						'bottom' => 'Bottom',
					),
					'default_value' => 'side',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_65201753e18c0',
					'label' => 'Widget Type',
					'name' => 'widget_type',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'text' => 'Text',
						'custom_html' => 'Custom HTML',
						'media_image' => 'Image',
						'media_gallery' => 'Image Gallery',
						'recent' => 'Recent Posts',
						'categories' => 'Categories',
						'em_calendar' => 'EM Calendar',
						'ninja_forms_widget' => 'Ninja Forms',
						'wcpbc_products_by_category' => 'WC Products by Category',
						'post_widget' => 'Post Widget',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6542c518a7cc5',
					'label' => 'Target by Post/Location',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_655b7a3ea6813',
					'label' => 'Targeting disabled',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'show',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'hide',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => 'Because the snippet is currently set to <strong>Show/Hide <em>everywhere</em></strong>, additional targeting logic is disabled.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_651daf0786659',
					'label' => 'Target by Post Type',
					'name' => 'target_by_post_type',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => 'Use this option to target individual (singular) post pages per post type.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => 'checklist',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'all' => 'All singular posts',
						'post' => 'Posts',
						'page' => 'Pages',
						'event' => 'Events',
						'event_series' => 'Event Series',
						'location' => 'Locations',
						'repertoire' => 'Musical Works',
						'person' => 'People',
						'product' => 'Products',
						'sermon' => 'Sermons',
						'sermon_series' => 'Sermon Series',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 1,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key' => 'field_654d1d49f87f0',
					'label' => 'Target by Post Type Archive',
					'name' => 'target_by_post_type_archive',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => 'Use this option to target archive pages per post type.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => 'checklist',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'all' => 'All Archives',
						'post' => 'Post Archives',
						'page' => 'Page Archives',
						'event' => 'Event Archives',
						'event_series' => 'Event Series Archives',
						'location' => 'Location Archives',
						'repertoire' => 'Musical Works Archives',
						'person' => 'People Archives',
						'product' => 'Product Archives',
						'sermon' => 'Sermon Archives',
						'sermon_series' => 'Sermon Series Archives',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 1,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key' => 'field_651daf528665a',
					'label' => 'Target by Site Location',
					'name' => 'target_by_location',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '34',
						'class' => 'checklist',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'is_home' => 'Homepage',
						'is_search' => 'Search Results',
						'is_page' => 'All individual pages',
						'is_archive' => 'All post archives',
						'is_attachment' => 'All attachments',
						'is_category' => 'All category archives',
						'is_tag' => 'All tag archives',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 0,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key' => 'field_653009364ca3d',
					'label' => 'Widget Logic Custom Post Types/Taxonomies',
					'name' => 'widget_logic_custom_post_types_taxonomies',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'DO NOT EDIT!',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '66',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_653009124ca3c',
					'label' => 'Widget Logic Location',
					'name' => 'widget_logic_location',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'DO NOT EDIT!',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '34',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6529654e827dc',
					'label' => 'Taxonomies',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_655b7adab6763',
					'label' => 'Targeting disabled',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'show',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'hide',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => 'Because the snippet is currently set to <strong>Show/Hide <em>everywhere</em></strong>, additional targeting logic is disabled.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_651dad2686087',
					'label' => 'Target by Taxonomy',
					'name' => 'target_by_taxonomy',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_653c3e9089c6a',
					'label' => 'Target Taxonomy Archives',
					'name' => 'target_by_taxonomy_archive',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'checklist',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'event-categories' => 'All "Event Categories" archives',
						'repertoire_category' => 'All "Repertoire Categories" archives',
						'sermon_topic' => 'All "Sermon Topics" archives',
						'product_cat' => 'All "Product Category" archives',
						'product_tag' => 'All "Product Tag" archives',
						'product_shipping_class' => 'All "Shipping Class" archives',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 0,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key' => 'field_65331d7f3bb68',
					'label' => 'Widget Logic Taxonomies (Tax:Term Pairs)',
					'name' => 'widget_logic_taxonomy',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'DO NOT EDIT!',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'checklist readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_65288fc9dd084',
					'label' => 'URL/Post Conditions',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_655b7af0b6764',
					'label' => 'Targeting disabled',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'show',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'hide',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => 'Because the snippet is currently set to <strong>Show/Hide <em>everywhere</em></strong>, additional targeting logic is disabled.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_65305e8797803',
					'label' => 'Target by URL (Repeater)',
					'name' => 'target_by_url',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => 'Use this field ONLY to target URLs of category pages and the like, NOT for individual posts of any post type.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_6530630a97804',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6530630a97804',
							'label' => 'URL',
							'name' => 'url',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'relevanssi_exclude' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_65305e8797803',
						),
					),
				),
				array(
					'key' => 'field_65306bc897805',
					'label' => 'Exclude by URL (Repeater)',
					'name' => 'exclude_by_url',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => 'Use this field ONLY to exclude URLs of category pages and the like, NOT for individual posts of any post type.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_65306bc897806',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_65306bc897806',
							'label' => 'URL',
							'name' => 'url',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'relevanssi_exclude' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_65306bc897805',
						),
					),
				),
				array(
					'key' => 'field_651dab1d12566',
					'label' => 'Target by Post',
					'name' => 'target_by_post',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'post_type' => '',
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'allow_null' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_651dab5c12567',
					'label' => 'Exclude by Post',
					'name' => 'exclude_by_post',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'post_type' => '',
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'allow_null' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(),
				),
				array(
					'key' => 'field_65288f56a8bab',
					'label' => 'Target by URL (BK)',
					'name' => 'widget_logic_target_by_url',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_65288f7aa8bac',
					'label' => 'Exclude by URL (BK)',
					'name' => 'widget_logic_exclude_by_url',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6552b4893e436',
					'label' => 'CS Post IDs',
					'name' => 'cs_post_ids',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'conditional',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'selected',
							),
						),
						array(
							array(
								'field' => 'field_651ef6d23b1aa',
								'operator' => '==',
								'value' => 'notselected',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6556c832910e1',
					'label' => 'Image Fields',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_6556c84a910e2',
					'label' => 'Attachment ID',
					'name' => 'attachment_id',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'TMP/Transitional',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6556c88976dce',
					'label' => 'Image Title',
					'name' => 'image_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'TMP/Transitional',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6556c89976dcf',
					'label' => 'Link Type',
					'name' => 'link_type',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'TMP/Transitional',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6556c8b276dd0',
					'label' => 'Link URL',
					'name' => 'link_url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'TMP/Transitional',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6520170ce18be',
					'label' => 'Legacy Fields',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_655b80eb416c1',
					'label' => 'Do Not Edit!',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => 'Do not edit the values in these legacy fields! Dev only!',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_65201796e18c1',
					'label' => 'Widget ID',
					'name' => 'widget_id',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6525a60968f9f',
					'label' => 'Widget UID',
					'name' => 'widget_uid',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_652017b44b566',
					'label' => 'Legacy Sidebar ID(s)',
					'name' => 'sidebar_id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6536b4e8fde0d',
					'label' => 'Sidebar Sortnum',
					'name' => 'sidebar_sortnum',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'Legacy value based on Custom Sidebars',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => 0,
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_65675d7370810',
					'label' => 'Post IDs',
					'name' => 'post_ids',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'For snippets created from post_sidebar_widget_content',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_655b8dbf184f4',
					'label' => 'Post ID [TMP -- DELETE!]',
					'name' => 'post_id',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'For snippets created from post_sidebar_widget_content',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_65260772851c1',
					'label' => 'Widget Logic',
					'name' => 'widget_logic',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_65269c178ee0d',
					'label' => 'WIP',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_65269c258ee0e',
					'label' => 'Snippet Taxonomies WIP',
					'name' => 'snippet_taxonomies',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'readonly',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'taxonomy' => 'category',
					'add_term' => 0,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'id',
					'field_type' => 'checkbox',
					'bidirectional' => 0,
					'multiple' => 0,
					'allow_null' => 0,
					'bidirectional_target' => array(),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'snippet',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal', // 'acf_after_title'
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		) );
    }
}
