<?php
/**
 * whx4 field groups
 *
 * @link https://www.advancedcustomfields.com/resources/???
 */

/**
 * Check if ACF PRO is active and function exists
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}
	
add_action( 'acf/include_fields', 'whx4_register_field_groups' );


function whx4_register_field_groups() {

	// WIP!!!!
	acf_add_local_field_group( array(
		'key' => 'group_whx4_person',
		//'key' => 'group_624775b57f8df',
		'title' => 'WHx4 Person: Additional Fields',
		'fields' => array(
			array(
				'key'	=> 'field_whx4_person_basics_tab'
				//'key' => 'field_64b065b9a96c5',
				'label' => 'Person Basics',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=> 'field_whx4_first_name'
				//'key' => 'field_624775c6b621b',
				'label' => 'First Name',
				'name' => 'first_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_middle_name'
				//'key' => 'field_624775d1b621c',
				'label' => 'Middle Name',
				'name' => 'middle_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=> 'field_whx4_last_name'
				//'key' => 'field_624775dbb621d',
				'label' => 'Last Name',
				'name' => 'last_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_initials'
				//'key' => 'field_624775e3b621e',
				'label' => 'Initials',
				'name' => 'initials',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '7',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=> 'field_whx4_prefix'
				//'key' => 'field_624775eab621f',
				'label' => 'Prefix',
				'name' => 'prefix',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_suffix'
				//'key' => 'field_624775eeb6220',
				'label' => 'Suffix',
				'name' => 'suffix',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_job_title'
				//'key' => 'field_624775f4b6221',
				'label' => 'Job Title',
				'name' => 'job_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_website'
				//'key' => 'field_624775f9b6222',
				'label' => 'Website',
				'name' => 'website',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key'	=> 'field_whx4_email_address'
				//'key' => 'field_62477603b6223',
				'label' => 'Email Address',
				'name' => 'email_address',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=> 'field_whx4_phone_number'
				//'key' => 'field_6247760db6224',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_birth_year'
				//'key' => 'field_6247761bb6225',
				'label' => 'Birth Year',
				'name' => 'birth_year',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_death_year'
				//'key' => 'field_62477625b6226',
				'label' => 'Death Year',
				'name' => 'death_year',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_dates'
				//'key' => 'field_62477629b6227',
				'label' => 'Dates',
				'name' => 'dates',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=> 'field_whx4_user_account'
				//'key' => 'field_6247762db6228',
				'label' => 'User Account',
				'name' => 'user_account',
				'aria-label' => '',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'role' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'array',
				'bidirectional_target' => array(
				),
			),
			array(
				'key'	=> 'field_whx4_special_name'
				//'key' => 'field_64876136e25a3',
				'label' => 'Special Name',
				'name' => 'special_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'This field is ONLY to be used in very special cases, i.e. "The Boss", or "The Rector". It will supersede all other name fields in event programs.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=> 'field_whx4_media'
				//'key' => 'field_64b065e9a96c7',
				'label' => 'Media',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=> 'field_whx4_image_gallery'
				//'key' => 'field_64b06589b33da',
				'label' => 'Image Gallery',
				'name' => 'image_gallery',
				'aria-label' => '',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'return_format' => 'id',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'insert' => 'append',
				'preview_size' => 'medium',
			),
			array(
				'key'	=> 'field_whx4_notes_tab'
				//'key' => 'field_64b065d2a96c6',
				'label' => 'Notes',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=> 'field_whx4_notes'
				//'key' => 'field_6247763bb6229',
				'label' => 'Notes',
				'name' => 'notes',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key'	=> 'field_whx4_affiliations_tab'
				//'key' => 'field_664c8a5fcb582',
				'label' => 'Affiliations',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=> 'field_whx4_affiliations'
				//'key' => 'field_664c8a72cb583',
				'label' => 'Affiliations',
				'name' => 'affiliations',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key'	=> 'field_whx4_affiliations_role'
						//'key' => 'field_664c8aa2cb585',
						'label' => 'Role',
						'name' => 'role',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'person_role',
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 1,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_whx4_affiliations',
					),
					array(
						'key'	=> 'field_whx4_affiliations_group'
						//'key' => 'field_664c8a86cb584',
						'label' => 'Group',
						'name' => 'group',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => array(
							0 => 'group',
						),
						'post_status' => '',
						'taxonomy' => '',
						'return_format' => 'object',
						'multiple' => 0,
						'allow_null' => 0,
						'bidirectional' => 0,
						'ui' => 1,
						'bidirectional_target' => array(
						),
						'parent_repeater' => 'field_whx4_affiliations',
					),
					array(
						'key'	=> 'field_whx4_affiliations_dates'
						//'key' => 'field_664c8bd2f2841',
						'label' => 'Dates',
						'name' => 'dates',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Dates of affiliation',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_affiliations',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

}

?>