<?php
/**
 * whx4 field groups
 *
 * @link https://www.advancedcustomfields.com/resources/???
 */

/**
 * Check if ACF PRO is active and function exists
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}

add_action( 'acf/include_fields', 'whx4_register_field_groups' );


function whx4_register_field_groups() {

	// group_whx4_person
	acf_add_local_field_group( array(
		'key' => 'group_whx4_person',
		//'key' => 'group_624775b57f8df',
		'title' => 'WHx4 Person: Additional Fields',
		'fields' => array(
			array(
				'key'	=>	'field_whx4_64b065b9a96c5',
				//'key'	=>	'field_whx4_person_basics_tab',
				//'key' => 'field_64b065b9a96c5',
				'label' => 'Person Basics',
				'name' => 'person_basics_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_624775c6b621b',
				//'key'	=>	'field_whx4_first_name',
				//'key' => 'field_624775c6b621b',
				'label' => 'First Name',
				'name' => 'first_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_624775d1b621c',
				//'key'	=>	'field_whx4_middle_name',
				//'key' => 'field_624775d1b621c',
				'label' => 'Middle Name',
				'name' => 'middle_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=>	'field_whx4_624775dbb621d',
				//'key'	=>	'field_whx4_last_name',
				//'key' => 'field_624775dbb621d',
				'label' => 'Last Name',
				'name' => 'last_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_624775e3b621e',
				//'key'	=>	'field_whx4_initials',
				//'key' => 'field_624775e3b621e',
				'label' => 'Initials',
				'name' => 'initials',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '7',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=>	'field_whx4_624775eab621f',
				//'key'	=>	'field_whx4_prefix',
				//'key' => 'field_624775eab621f',
				'label' => 'Prefix',
				'name' => 'prefix',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_624775eeb6220',
				//'key'	=>	'field_whx4_suffix',
				//'key' => 'field_624775eeb6220',
				'label' => 'Suffix',
				'name' => 'suffix',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_624775f4b6221',
				//'key'	=>	'field_whx4_job_title',
				//'key' => 'field_624775f4b6221',
				'label' => 'Job Title',
				'name' => 'job_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_624775f9b6222',
				//'key'	=>	'field_whx4_website',
				//'key' => 'field_624775f9b6222',
				'label' => 'Website',
				'name' => 'website',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key'	=>	'field_whx4_62477603b6223',
				//'key'	=>	'field_whx4_email_address',
				//'key' => 'field_62477603b6223',
				'label' => 'Email Address',
				'name' => 'email_address',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=>	'field_whx4_6247760db6224',
				//'key'	=>	'field_whx4_phone_number',
				//'key' => 'field_6247760db6224',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_6247761bb6225',
				//'key'	=>	'field_whx4_birth_year',
				//'key' => 'field_6247761bb6225',
				'label' => 'Birth Year',
				'name' => 'birth_year',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_62477625b6226',
				//'key'	=>	'field_whx4_death_year',
				//'key' => 'field_62477625b6226',
				'label' => 'Death Year',
				'name' => 'death_year',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_62477629b6227',
				//'key'	=>	'field_whx4_dates',
				//'key' => 'field_62477629b6227',
				'label' => 'Dates',
				'name' => 'dates',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_6247762db6228',
				//'key'	=>	'field_whx4_user_account',
				//'key' => 'field_6247762db6228',
				'label' => 'User Account',
				'name' => 'user_account',
				'aria-label' => '',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'float-left',
					'id' => '',
				),
				'role' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'array',
				'bidirectional_target' => array(),
			),
			array(
				'key'	=>	'field_whx4_64876136e25a3',
				//'key'	=>	'field_whx4_special_name',
				//'key' => 'field_64876136e25a3',
				'label' => 'Special Name',
				'name' => 'special_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'This field is ONLY to be used in very special cases, i.e. "The Boss", or "The Rector". It will supersede all other name fields in event programs.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_whx4_person_ids',
				'label' => 'Identities',
				'name' => 'identities',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'identity',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'id',
				'multiple' => 1,
				'save_custom' => 1,
				'save_post_type' => 'identity',
				'save_post_status' => 'publish',
				/*'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '1',
					'acfe_bidirectional_related' => array(
						0 => 'field_whx4_identity_person',
					),
				),*/
				'bidirectional' => 1,
				'bidirectional_target' => array(
					0 => 'field_whx4_identity_person',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 1,
			),
			array(
				'key'	=>	'field_whx4_64b065e9a96c7',
				//'key'	=>	'field_whx4_media_tab',
				//'key' => 'field_64b065e9a96c7',
				'label' => 'Media',
				'name' => 'media_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_64b06589b33da',
				//'key'	=>	'field_whx4_image_gallery',
				//'key' => 'field_64b06589b33da',
				'label' => 'Image Gallery',
				'name' => 'image_gallery',
				'aria-label' => '',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'return_format' => 'id',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'insert' => 'append',
				'preview_size' => 'medium',
			),
			array(
				'key'	=>	'field_whx4_64b065d2a96c6',
				//'key'	=>	'field_whx4_notes_tab',
				//'key' => 'field_64b065d2a96c6',
				'label' => 'Notes',
				'name' => 'notes_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_6247763bb6229',
				//'key'	=>	'field_whx4_notes',
				//'key' => 'field_6247763bb6229',
				'label' => 'Notes',
				'name' => 'notes',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key'	=>	'field_whx4_664c8a5fcb582',
				//'key'	=>	'field_whx4_affiliations_tab',
				//'key' => 'field_664c8a5fcb582',
				'label' => 'Affiliations and Identities [DEPRECATED]',
				//'label' => 'Titles and Affiliations',
				'name' => 'affiliations_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '22',
					'class' => 'float-left',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_664c8a72cb583',
				//'key'	=>	'field_whx4_affiliations',
				//'key' => 'field_664c8a72cb583',
				'label' => 'Affiliations',
				'name' => 'affiliations',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key'	=>	'field_whx4_664c8aa2cb585',
						//'key'	=>	'field_whx4_affiliations_role',
						//'key' => 'field_664c8aa2cb585',
						'label' => 'Role',
						'name' => 'role',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'person_role',
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 1,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_affiliations',
					),
					// TODO: decide whether separate 'title' field is useful
					// Consider event-specific titles vs. group-affiliated titles -- might be e.g. Soprano with Musica Sacra but also Soprano Soloist with Sacra for a specific concert...
					/*array(
						'key'	=>	'field_whx4_affiliations_title',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'person_title',
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 1,
						'bidirectional' => 0,
						'multiple' => 0,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_affiliations',
					),*/
					array(
						'key'	=>	'field_whx4_664c8a86cb584',
						//'key'	=>	'field_whx4_affiliations_group',
						//'key' => 'field_664c8a86cb584',
						'label' => 'Group', // TODO: add option to designate "At large" if title relates to no specific group/org
						'name' => 'group',
						'aria-label' => '',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_at_large',
									'operator' => '==',
									'value' => '0',
								),
							),
						),
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => array(
							0 => 'group',
						),
						'post_status' => '',
						'taxonomy' => '',
						'return_format' => 'id',
						'multiple' => 0,
						'allow_null' => 0,
						'bidirectional' => 0,
						'ui' => 1,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_affiliations',
					),
					array(
						'key'	=>	'field_whx4_664c8bd2f2841',
						//'key'	=>	'field_whx4_affiliations_dates',
						//'key' => 'field_664c8bd2f2841',
						'label' => 'Dates',
						'name' => 'dates',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Dates of affiliation/activity',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_affiliations',
					),
					array(
						'key' => 'field_whx4_at_large',
						'label' => 'At Large',
						'name' => 'at_large',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => 'Preferred general title', //'Check this box if this is the person\'s preferred general title, not in affiliation with any specific group',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '10',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'parent_repeater' => 'field_whx4_affiliations',
					),
					array(
						'key' => 'field_whx4_current_role',
						'label' => 'Current Role?',
						'name' => 'current_role',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '10',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'parent_repeater' => 'field_whx4_affiliations',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	//
	acf_add_local_field_group( array(
		'key' => 'group_5f15964995660',
		'title' => 'WHx4 Person: Legacy Fields',
		'fields' => array(
			array(
				'key' => 'field_5f159658d7070',
				'label' => 'Last Name Var',
				'name' => 'last_name_var',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f15967cd7071',
				'label' => 'Display Name Var',
				'name' => 'display_name_var',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f159690d7072',
				'label' => 'Prefix Var',
				'name' => 'prefix_var',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f15969fd7073',
				'label' => 'Job Title Var',
				'name' => 'job_title_var',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f1596e4d7076',
				'label' => 'Website Variant',
				'name' => 'website_var',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5f1596b8d7074',
				'label' => 'Legacy ID',
				'name' => 'legacy_id',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5f1596d5d7075',
				'label' => 'Parent ID',
				'name' => 'parent_id',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'person',
				),
				array(
					'param' => 'current_user_role',
					'operator' => '==',
					'value' => 'administrator',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => false,
	) );
	
	// group_whx4_identity	
	acf_add_local_field_group( array(
		'key' => 'group_whx4_identity',
		//'key' => 'group_67054bd382b5f',
		'title' => 'WHx4 Identity: Additional Fields',
		'fields' => array(
			array(
				'key' => 'field_whx4_identity_person',
				'label' => 'Person',
				'name' => 'person',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'person',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'save_custom' => 0,
				'save_post_status' => 'publish',
				/*'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '1', // true
					'acfe_bidirectional_related' => array(
						0 => 'field_whx4_person_ids', //0 => 'field_67054d2298e2a',
					),
				),*/
				'bidirectional' => 1,
				'bidirectional_target' => array(
					0 => 'field_whx4_person_ids',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 1,
				'save_post_type' => '',
			),
			array(
				'key' => 'field_whx4_identity_role',
				'label' => 'Role',
				'name' => 'role',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'person_role',
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'field_type' => 'select',
				'allow_null' => 0,
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_in_bindings' => 1,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_whx4_identity_first_name',
				'label' => 'First Name',
				'name' => 'first_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_whx4_identity_last_name',
				'label' => 'Last Name',
				'name' => 'last_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_whx4_identity_email',
				'label' => 'Email Address',
				'name' => 'email_address',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_whx4_identity_group',
				'label' => 'Group',
				'name' => 'group',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'e.g. Employer(s)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'group',
				),
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'id',
				'multiple' => 1,
				'save_custom' => 0,
				'save_post_status' => 'publish',
				'acfe_bidirectional' => array(
					'acfe_bidirectional_enabled' => '0',
				),
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
				'save_post_type' => '',
			),
			array(
				'key' => 'field_whx4_identity_current',
				'label' => 'Current?',
				'name' => 'current',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'Box checked indicates current/active identity/role/affiliation',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'message' => '',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_identity_dates',
				'label' => 'Dates',
				'name' => 'dates',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Dates of affiliation/activity',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'identity',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		//
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );
	
	//
	acf_add_local_field_group( array(
		'key' => 'group_664b76ebf3872',
		'title' => 'People Module Options',
		'fields' => array(
			array(
				'key' => 'field_664b76eb1110b',
				'label' => 'Short Format Title Display Formula',
				'name' => 'person_title_form_short',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_664b777b1110c',
				'label' => 'Medium Format Title Display Formula',
				'name' => 'person_title_form_medium',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_664b77881110d',
				'label' => 'Long Format Title Display Formula',
				'name' => 'person_title_form_long',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'people-module-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	// group_whx4_group
	acf_add_local_field_group( array(
		'key' => 'group_whx4_group',
		//'key' => 'group_62745b70d177e',
		'title' => 'WHx4 Group: Additional Fields',
		'fields' => array(
			array(
				'key'	=>	'field_whx4_665a0045f05e9',
				//'key'	=>	'field_whx4_group_website',
				//'key' => 'field_665a0045f05e9',
				'label' => 'Primary Website',
				'name' => 'website',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'group',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'This post type is for managing groups of persons, including: organizations, educational and religious institutions, ensembles, companies, etc.',
		'show_in_rest' => 0,
	) );
	
	// group_whx4_pp
	acf_add_local_field_group( array(
		'key' => 'group_whx4_pnp',
		//'key' => 'group_5efa556eba291',
		'title' => 'WHx4: Personnel & Program',
		'fields' => array(
			array(
				'key'	=>	'field_whx4_606b4d8173944',
				//'key'	=>	'field_whx4_show_all_fields',
				//'key' => 'field_606b4d8173944',
				'label' => 'Show all fields',
				'name' => 'show_all_fields',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'For CMS use *only*. Checking this box will disable the conditional showing/hiding of fields for this record, which is useful if you need to clear out obsolete values from hidden fields.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_62d58e52c3e73',
				//'key'	=>	'field_whx4_program_options_tab',
				//'key' => 'field_62d58e52c3e73',
				'label' => 'Program Options',
				'name' => 'program_options_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_62d58d97c3e70',
				//'key'	=>	'field_whx4_program_order',
				//'key' => 'field_62d58d97c3e70',
				'label' => 'Program Order',
				'name' => 'program_order',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => 'Display order of the two program sections.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'first_personnel' => 'Personnel first (default)',
					'first_program_items' => 'Program items first',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
			array(
				'key'	=>	'field_whx4_62d58ddac3e71',
				//'key'	=>	'field_whx4_program_type',
				//'key' => 'field_62d58ddac3e71',
				'label' => 'Program Type',
				'name' => 'program_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'service_order' => 'Service Order (default)',
					'concert_program' => 'Concert Program',
				),
				'default_value' => 'service_order',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key'	=>	'field_whx4_62d58e1fc3e72',
				//'key'	=>	'field_whx4_program_layout',
				//'key' => 'field_62d58e1fc3e72',
				'label' => 'Program Layout',
				'name' => 'program_layout',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left_aligned' => 'Left-aligned (default)',
					'centered' => 'Centered',
				),
				'default_value' => 'left_aligned',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key'	=>	'field_whx4_61cb8e891b351',
				//'key'	=>	'field_whx4_personnel_tab',
				//'key' => 'field_61cb8e891b351',
				'label' => 'Personnel',
				'name' => 'personnel_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_62ebf3e9db2bf',
				//'key'	=>	'field_whx4_personnel_header',
				//'key' => 'field_62ebf3e9db2bf',
				'label' => 'Personnel Header',
				'name' => 'personnel_header',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_5ca37c2294f61',
				//'key'	=>	'field_whx4_personnel',
				//'key' => 'field_5ca37c2294f61',
				'label' => 'Event Personnel',
				'name' => 'personnel',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key'	=>	'field_whx4_64821af3cf797',
						//'key'	=>	'field_whx4_personnel_row_type',
						//'key' => 'field_64821af3cf797',
						'label' => 'Row Type',
						'name' => 'row_type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							'default' => 'Standard two-column row',
							'header' => 'Header row',
							'role_only' => 'Person role only',
							'name_only' => 'Person name only',
						),
						'default_value' => false,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_5fc697d3bdf47',
						//'key'	=>	'field_whx4_personnel_show_row',
						//'key' => 'field_5fc697d3bdf47',
						'label' => 'Show row on front end?',
						'name' => 'show_row',
						'aria-label' => '',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel',
									'operator' => '!=empty',
								),
							),
						),
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							0 => 'No',
							1 => 'Yes',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'allow_null' => 0,
						'other_choice' => 0,
						'layout' => 'vertical',
						'save_other_choice' => 0,
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_648882d91c62f',
						//'key'	=>	'field_whx4_personnel_header_txt',
						//'key' => 'field_648882d91c62f',
						'label' => 'Header Text',
						'name' => 'header_txt',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '==',
									'value' => 'header',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_5f07163e0289f',
						//'key'	=>	'field_whx4_personnel_role',
						//'key' => 'field_5f07163e0289f',
						'label' => 'Role',
						'name' => 'role',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'name_only',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'person_role',
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 1,
						'multiple' => 0,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_5dd74c99a74b3',
						//'key'	=>	'field_whx4_personnel_role_txt',
						//'key' => 'field_5dd74c99a74b3',
						'label' => 'Role (placeholder)',
						'name' => 'role_txt',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'name_only',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_5f074db904caa',
						//'key'	=>	'field_whx4_personnel_role_old',
						//'key' => 'field_5f074db904caa',
						'label' => 'Role (old)',
						'name' => 'role_old',
						'aria-label' => '',
						'type' => 'relationship',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel_role_txt',
									'operator' => '==empty',
								),
								array(
									'field' => 'field_whx4_personnel_role',
									'operator' => '==empty',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'name_only',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => '',
						'post_status' => '',
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
						),
						'return_format' => 'id',
						'min' => '',
						'max' => '',
						'elements' => '',
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_5ca37c2297392',
						//'key'	=>	'field_whx4_personnel_person',
						//'key' => 'field_5ca37c2297392',
						'label' => 'Person or Group/Ensemble',
						'name' => 'person',
						'aria-label' => '',
						'type' => 'relationship',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel_person_txt',
									'operator' => '==empty',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'role_only',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => array(
							0 => 'person',
							1 => 'identity',
							2 => 'group',
						),
						'post_status' => '',
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
							1 => 'post_type',
							2 => 'taxonomy',
						),
						'return_format' => 'id',
						'min' => '',
						'max' => '',
						'elements' => '',
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_5db4a1cffec0d',
						//'key'	=>	'field_whx4_personnel_person_txt',
						//'key' => 'field_5db4a1cffec0d',
						'label' => 'Person (placeholder)',
						'name' => 'person_txt',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'TMP use only',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_personnel_person',
									'operator' => '==empty',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
								array(
									'field' => 'field_whx4_personnel_row_type',
									'operator' => '!=',
									'value' => 'role_only',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_personnel',
					),
					array(
						'key'	=>	'field_whx4_62ea94927dcc0',
						//'key'	=>	'field_whx4_personnel_url',
						//'key' => 'field_62ea94927dcc0',
						'label' => 'Personnel URL',
						'name' => 'person_url',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_whx4_personnel',
					),
				),
			),
			array(
				'key'	=>	'field_whx4_61cb8ede32983',
				//'key'	=>	'field_whx4_program_tab',
				//'key' => 'field_61cb8ede32983',
				'label' => 'Program/Service Order',
				'name' => 'program_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_62ebf3fbdb2c0',
				//'key'	=>	'field_whx4_program_items_header',
				//'key' => 'field_62ebf3fbdb2c0',
				'label' => 'Program Items Header',
				'name' => 'program_items_header',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_5ca37044a92cc',
				//'key'	=>	'field_whx4_program_items',
				//'key' => 'field_5ca37044a92cc',
				'label' => 'Program Items',
				'name' => 'program_items',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => 'field_whx4_program_item',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key'	=>	'field_whx4_62eacaf65f6b6',
						//'key'	=>	'field_whx4_program_row_type',
						//'key' => 'field_62eacaf65f6b6',
						'label' => 'Row Type',
						'name' => 'row_type',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							'default' => 'Standard two-column row',
							'header' => 'Header row',
							'program_note' => 'Program note',
							'label_only' => 'Item label only',
							'title_only' => 'Item title only',
						),
						'default_value' => false,
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'parent_repeater' => 'field_whx4_program_items',
					),
					array(
						'key'	=>	'field_whx4_5fc691294bd5d',
						//'key'	=>	'field_whx4_program_show_row',
						//'key' => 'field_5fc691294bd5d',
						'label' => 'Show row on front end?',
						'name' => 'show_row',
						'aria-label' => '',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
							array(
								array(
									'field' => 'field_whx4_program_items',
									'operator' => '!=empty',
								),
							),
						),
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							0 => 'No',
							1 => 'Yes',
						),
						'default_value' => 0,
						'return_format' => 'value',
						'allow_null' => 0,
						'other_choice' => 0,
						'layout' => 'horizontal',
						'save_other_choice' => 0,
						'parent_repeater' => 'field_whx4_program_items',
					),
					/*array(
						'key'	=>	'field_whx4_5dabb3bf460cb',
						//'key'	=>	'field_whx4_program_is_header',
						//'key' => 'field_5dabb3bf460cb',
						'label' => 'Header?',
						'name' => 'is_header',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => 'DEPRECATED',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => 'deprecated',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'parent_repeater' => 'field_whx4_program_items',
					),*/
					/*array(
						'key'	=>	'field_whx4_61e7118ce01da',
						//'key'	=>	'field_whx4_program_show_item_label',
						//'key' => 'field_61e7118ce01da',
						'label' => 'Show the item label?',
						'name' => 'show_item_label',
						'aria-label' => '',
						'type' => 'radio',
						'instructions' => 'DEPRECATED',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => 'deprecated',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							0 => 'No',
							1 => 'Yes',
						),
						'default_value' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
						'other_choice' => 0,
						'layout' => 'horizontal',
						'save_other_choice' => 0,
						'parent_repeater' => 'field_whx4_program_items',
					),*/
					/*array(
						'key'	=>	'field_whx4_606b69d4ee6e5',
						//'key'	=>	'field_whx4_program_show_item_title',
						//'key' => 'field_606b69d4ee6e5',
						'label' => 'Show the item title?',
						'name' => 'show_item_title',
						'aria-label' => '',
						'type' => 'radio',
						'instructions' => 'DEPRECATED',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => 'deprecated',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'choices' => array(
							0 => 'No',
							1 => 'Yes',
						),
						'default_value' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
						'other_choice' => 0,
						'layout' => 'horizontal',
						'save_other_choice' => 0,
						'parent_repeater' => 'field_whx4_program_items',
					),*/
					array(
						'key'	=>	'field_whx4_5f072115a9b59',
						//'key'	=>	'field_whx4_program_item_label',
						//'key' => 'field_5f072115a9b59',
						'label' => 'Item Label',
						'name' => 'item_label',
						'aria-label' => '',
						'type' => 'taxonomy',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'title_only',
								),
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'program_note',
								),
							),
						),
						'wrapper' => array(
							'width' => '35',
							'class' => 'float-left clear-left',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'taxonomy' => 'program_label',
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'field_type' => 'select',
						'allow_null' => 1,
						'multiple' => 0,
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_program_items',
					),
					array(
						'key'	=>	'field_whx4_5e35f1cbd325b',
						//'key'	=>	'field_whx4_program_item_label_txt',
						//'key' => 'field_5e35f1cbd325b',
						'label' => 'Item Label (placeholder)',
						'name' => 'item_label_txt',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'title_only',
								),
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'program_note',
								),
							),
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '==',
									'value' => 'label_only',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '25',
							'class' => 'float-left',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_program_items',
					),
					array(
						'key'	=>	'field_whx4_5ca37044aafbb',
						//'key'	=>	'field_whx4_program_item',
						//'key' => 'field_5ca37044aafbb',
						'label' => 'Program Item',
						'name' => 'program_item',
						'aria-label' => '',
						'type' => 'relationship',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'program_note',
								),
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'label_only',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'post_type' => array(
							0 => 'person',
							1 => 'repertoire',
							2 => 'reading',
							3 => 'sermon',
						),
						'post_status' => '',
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
							1 => 'post_type',
							2 => 'taxonomy',
						),
						'return_format' => 'id',
						'min' => '',
						'max' => '',
						'elements' => '',
						'bidirectional_target' => array(),
						'parent_repeater' => 'field_whx4_program_items',
					),
					array(
						'key'	=>	'field_whx4_5db1bbf21b703',
						//'key'	=>	'field_whx4_program_item_txt',
						//'key' => 'field_5db1bbf21b703',
						'label' => 'Program Item (placeholder)',
						'name' => 'program_item_txt',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'label_only',
								),
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
							),
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '==',
									'value' => 'title_only',
								),
							),
							array(
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '==',
									'value' => 'program_note',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_program_items',
					),
					array(
						'key'	=>	'field_whx4_5e63ef849c7aa',
						//'key'	=>	'field_whx4_program_item_title_for_matching',
						//'key' => 'field_5e63ef849c7aa',
						'label' => 'Program Item Title for Matching (TXT)',
						'name' => 'program_item_title_for_matching',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_whx4_program_item_txt',
									'operator' => '!=empty',
								),
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'header',
								),
								array(
									'field' => 'field_whx4_program_row_type',
									'operator' => '!=',
									'value' => 'program_note',
								),
							),
							array(
								array(
									'field' => 'field_whx4_show_all_fields',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_whx4_program_items',
					),
					array(
						'key'	=>	'field_whx4_637662633faf3',
						//'key'	=>	'field_whx4_program_item_note',
						//'key' => 'field_637662633faf3',
						'label' => 'Program Item Note',
						'name' => 'program_item_note',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'relevanssi_exclude' => 0,
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_whx4_program_items',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event-recurring',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'project',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	// group_whx4_event
	acf_add_local_field_group( array(
		'key' => 'group_whx4_event',
		//'key' => 'group_5efa556eba291',
		'title' => 'WHx4 Event: Additional Fields',
		'fields' => array(
			/*array(
				'key'	=>	'field_whx4_606b4d8173944',
				//'key'	=>	'field_whx4_show_all_fields',
				//'key' => 'field_606b4d8173944',
				'label' => 'Show all fields',
				'name' => 'show_all_fields',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'For CMS use *only*. Checking this box will disable the conditional showing/hiding of fields for this record, which is useful if you need to clear out obsolete values from hidden fields.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),*/
			array(
				'key' => 'field_whx4_series_tab',
				'label' => 'Event Series',
				'name' => 'series_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_632a27ff8450f',
				//'key' => 'field_632a27ff8450f',
				'label' => 'Event Series (v2 bidirectional)',
				'name' => 'event_series',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'post_type' => array(
					0 => 'event_series',
				),
				'post_status' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'return_format' => 'id',
				'min' => '',
				'max' => '',
				'elements' => '',
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key'	=>	'field_whx4_627bf1670a5a7',
				//'key'	=>	'field_whx4_event_series',
				//'key' => 'field_627bf1670a5a7',
				'label' => 'Event Series (v1)',
				'name' => 'event_series_v1',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'post_type' => array(
					0 => 'event_series',
				),
				'post_status' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'return_format' => 'id',
				'min' => '',
				'max' => '',
				'elements' => '',
				'bidirectional' => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key'	=>	'field_whx4_61cb8ef332984',
				//'key'	=>	'field_whx4_event_ticketing_tab',
				//'key' => 'field_61cb8ef332984',
				'label' => 'Ticketing',
				'name' => 'ticketing_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_6313b5b1a968b',
				//'key'	=>	'field_whx4_show_ticketing_info',
				//'key' => 'field_6313b5b1a968b',
				'label' => 'Show Ticketing Info?',
				'name' => 'show_ticketing_info',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes, show it on the front end',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_63125380297ab',
				//'key'	=>	'field_whx4_ticket_info_header',
				//'key' => 'field_63125380297ab',
				'label' => 'Ticket Info Header',
				'name' => 'ticket_info_header',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'e.g. "Tickets"',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '80',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_63125393297ac',
				//'key'	=>	'field_whx4_ticket_info',
				//'key' => 'field_63125393297ac',
				'label' => 'Ticket Info',
				'name' => 'ticket_info',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key'	=>	'field_whx4_631253b7297ad',
				//'key'	=>	'field_whx4_show_ticketing_urls',
				//'key' => 'field_631253b7297ad',
				'label' => 'Show Ticketing URLs?',
				'name' => 'show_ticketing_urls',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes, show them on the front end',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_62eaf8a23a21f',
				//'key'	=>	'field_whx4_ticket_urls',
				//'key' => 'field_62eaf8a23a21f',
				'label' => 'Ticket URLs',
				'name' => 'ticket_urls',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key'	=>	'field_whx4_62eaf8e03a221',
						//'key'	=>	'field_whx4_ticket_url_link_text',
						//'key' => 'field_62eaf8e03a221',
						'label' => 'Ticket URL Link Text',
						'name' => 'ticket_url_link_text',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_whx4_ticket_urls',
					),
					array(
						'key'	=>	'field_whx4_63123f8f5da4a',
						//'key'	=>	'field_whx4_ovationtix_id',
						//'key' => 'field_63123f8f5da4a',
						'label' => 'OvationTix Event ID',
						'name' => 'ovationtix_id',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_whx4_ticket_urls',
					),
					array(
						'key'	=>	'field_whx4_62eaf8c83a220',
						//'key'	=>	'field_whx4_ticket_url',
						//'key' => 'field_62eaf8c83a220',
						'label' => 'Ticket URL',
						'name' => 'ticket_url',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => 'This field is only to be used if the ticket url is NOT in the form https://ci.ovationtix.com/35174/production/OVATIONTIX_ID',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '45',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_whx4_ticket_urls',
					),
				),
			),
			array(
				'key'	=>	'field_whx4_5efa5605dda35',
				//'key'	=>	'field_whx4_primary_ticket_url',
				//'key' => 'field_5efa5605dda35',
				'label' => 'Primary Ticket URL',
				'name' => 'ticket_url',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key'	=>	'field_whx4_5efa5613dda36',
				//'key'	=>	'field_whx4_primary_ticket_url_link_text',
				//'key' => 'field_5efa5613dda36',
				'label' => 'Primary Ticket URL Link Text',
				'name' => 'ticket_url_link_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_whx4_ticket_url',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Buy Tickets',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key'	=>	'field_whx4_63e69359ec29f',
				//'key'	=>	'field_whx4_bookings_tab',
				//'key' => 'field_63e69359ec29f',
				'label' => 'EM Booking Customizations',
				'name' => 'bookings_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_63e6936eec2a0',
				//'key'	=>	'field_whx4_booking_form_display',
				//'key' => 'field_63e6936eec2a0',
				'label' => 'Booking Form Display',
				'name' => 'booking_form_display',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'choices' => array(
					'modal' => 'Modal',
					'inline' => 'Inline',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key'	=>	'field_whx4_63e69397ec2a1',
				//'key'	=>	'field_whx4_booking_type',
				//'key' => 'field_63e69397ec2a1',
				'label' => 'Booking Type',
				'name' => 'booking_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'choices' => array(
					'registration' => 'Registration',
					'application' => 'Application',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key'	=>	'field_whx4_63e6da26b1b40',
				//'key'	=>	'field_whx4_booking_button_text',
				//'key' => 'field_63e6da26b1b40',
				'label' => 'Booking Button Text',
				'name' => 'booking_button_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '***NOT YET FUNCTIONAL*** This could in the future be used to set the text for the "Submit" button on the booking form.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=>	'field_whx4_63e6da8ecab77',
				//'key'	=>	'field_whx4_booking_form_button_text',
				//'key' => 'field_63e6da8ecab77',
				'label' => 'Booking Form Button Text',
				'name' => 'booking_form_button_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'This is the text for the button that opens the booking form modal window.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_whx4_booking_form_display',
							'operator' => '==',
							'value' => 'modal',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'relevanssi_exclude' => 0,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key'	=>	'field_whx4_61cb8f0132985',
				//'key'	=>	'field_whx4_event_other_tab',
				//'key' => 'field_61cb8f0132985',
				'label' => 'Other',
				'name' => 'other_tab',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key'	=>	'field_whx4_5efa5626dda37',
				//'key'	=>	'field_whx4_event_hide_day_titles',
				//'key' => 'field_5efa5626dda37',
				'label' => 'Hide Day Titles?',
				'name' => 'hide_day_titles',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes, hide them',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_event_hide_special_notices',
				'label' => 'Hide Special Notices?',
				'name' => 'hide_special_notices',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes, hide them',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_5efa56750f99b',
				//'key'	=>	'field_whx4_event_title_uid',
				//'key' => 'field_5efa56750f99b',
				'label' => 'Title UID',
				'name' => 'title_uid',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event-recurring',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	// >> WHx4
	acf_add_local_field_group( array(
		'key' => 'group_5de541e8a5411',
		'title' => 'WHx4 Event: Legacy & Admin Fields',
		'fields' => array(
			array(
				'key' => 'field_5de5536875710',
				'label' => 'Legacy Event ID',
				'name' => 'legacy_event_id',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5de55382db1d0',
				'label' => 'Legacy Recurring ID',
				'name' => 'legacy_recurring_id',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5de55bccea408',
				'label' => 'Legacy All Day Event',
				'name' => 'legacy_all_day_event',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5de55be9ea409',
				'label' => 'Legacy Location',
				'name' => 'legacy_location',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5de55bfeea40a',
				'label' => 'Legacy Contact Name',
				'name' => 'legacy_contact_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5de55c04ea40b',
				'label' => 'Legacy Contact Email',
				'name' => 'legacy_contact_email',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5de55c14ea40c',
				'label' => 'Legacy Contact Phone',
				'name' => 'legacy_contact_phone',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5de55c20ea40d',
				'label' => 'Legacy RSVP Date',
				'name' => 'legacy_rsvp_date',
				'aria-label' => '',
				'type' => 'date_time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y g:i a',
				'return_format' => 'd/m/Y g:i a',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5de55c32ea40e',
				'label' => 'Legacy Leader',
				'name' => 'legacy_leader',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5de55c44ea40f',
				'label' => 'Legacy Friends of Music',
				'name' => 'legacy_friends_of_music',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5de55b211b728',
				'label' => 'Legacy Sidebar',
				'name' => 'legacy_sidebar',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5de5536875710',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
				array(
					'param' => 'current_user_role',
					'operator' => '==',
					'value' => 'administrator',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
				array(
					'param' => 'current_user_role',
					'operator' => '==',
					'value' => 'stc_administrator',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	// group_whx4_event_series
	acf_add_local_field_group( array(
		'key' => 'group_whx4_event_series',
		//'key' => 'group_627c0014d01c2',
		'title' => 'WHX4 Event Series: Additional Fields',
		'fields' => array(
			array(
				'key'	=>	'field_whx4_62a36344e2998',
				//'key' => 'field_62a36344e2998',
				'label' => 'Related Events (v2 bidirectional)',
				'name' => 'series_events',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'event',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
				'bidirectional' => 1,
				'bidirectional_target' => array(
					0 => 'field_whx4_632a27ff8450f',
				),
				//'bidirectional_target' => array(),
			),
			array(
				'key'	=>	'field_whx4_627c002205d63',
				//'key'	=>	'field_whx4_related_events',
				//'key' => 'field_627c002205d63',
				'label' => 'Related Events (v1)',
				'name' => 'related_events',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'event',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
				'bidirectional_target' => array(),
			),
			array(
				'key'	=>	'field_whx4_627c005e05d64',
				//'key'	=>	'field_whx4_series_hide_day_titles',
				//'key' => 'field_627c005e05d64',
				'label' => 'Hide Day Titles?',
				'name' => 'hide_day_titles',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'Hide day titles from display for all events in the series.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key'	=>	'field_whx4_627c008405d65',
				//'key'	=>	'field_whx4_prepend_series_title',
				//'key' => 'field_627c008405d65',
				'label' => 'Prepend Series Title for Individual Events?',
				'name' => 'prepend_series_title',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event_series',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	// group_whx4_
	// WIP

}
?>