<?php

namespace atc\WHx4\Modules\Events\Fields;

use atc\WHx4\Core\Contracts\FieldGroupInterface;

final class EventFields implements FieldGroupInterface
{
    public static function register(): void
    {
        //error_log( 'EventFields::register' );
        if ( !function_exists('acf_add_local_field_group') ) return;

        acf_add_local_field_group([
            'key'    => 'group_event_fields',
            'title'  => 'WHx4 Event Details',
            'fields' => [
                [
                    'key'   => 'field_whx4_events_start_date',
                    'label' => 'Start Date ',
                    'name'  => 'whx4_events_start_date',
                    'type'  => 'date_picker',
                    'display_format' => 'Y-m-d',
                    'return_format'  => 'Y-m-d',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key'   => 'field_whx4_events_start_time',
                    'label' => 'Start Time',
                    'name'  => 'whx4_events_start_time',
                    'type'  => 'time_picker',
                    'display_format' => 'H:i',
                    'return_format'  => 'H:i:s',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key'   => 'field_whx4_events_end_date',
                    'label' => 'End Date',
                    'name'  => 'whx4_events_end_date',
                    'type'  => 'date_picker',
                    'required' => 0,
                    'display_format' => 'Y-m-d',
                    'return_format'  => 'Y-m-d',
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key'   => 'field_whx4_events_end_time',
                    'label' => 'End Time',
                    'name'  => 'whx4_events_end_time',
                    'type'  => 'time_picker',
                    'required' => 0,
                    'display_format' => 'H:i',
                    'return_format'  => 'H:i:s',
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_whx4_events_is_recurring',
                    'label' => 'Recurring Event?',
                    'name' => 'whx4_events_is_recurring',
                    'type' => 'true_false',
                    'ui' => 1,
                ],
                // START recurrence rules WIP
                [
                    'key' => 'field_whx4_events_recurrence_human',
                    'label' => 'Repeats',
                    'name' => 'whx4_events_recurrence_human',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'field_whx4_events_freq',
                            'label' => 'Frequency',
                            'name' => 'freq',
                            'type' => 'select',
                            'choices' => [
                                'DAILY'   => 'Daily',
                                'WEEKLY'  => 'Weekly',
                                'MONTHLY' => 'Monthly',
                                'YEARLY'  => 'Yearly',
                            ],
                            'required' => 1,
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                        ],
                        [
                            'key' => 'field_whx4_events_interval',
                            'label' => 'Interval',
                            'name' => 'interval',
                            'type' => 'number',
                            'default_value' => 1,
                            'min' => 1,
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                        ],
                        [
                            'key' => 'field_whx4_events_byday',
                            'label' => 'Days of the Week',
                            'name' => 'byday',
                            'type' => 'checkbox',
                            'choices' => [
                                'MO' => 'Monday',
                                'TU' => 'Tuesday',
                                'WE' => 'Wednesday',
                                'TH' => 'Thursday',
                                'FR' => 'Friday',
                                'SA' => 'Saturday',
                                'SU' => 'Sunday',
                            ],
                            'conditional_logic' => [
                                [
                                    [
                                        'field' => 'field_whx4_events_freq',
                                        'operator' => '==',
                                        'value' => 'WEEKLY',
                                    ]
                                ]
                            ],
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                        ],
                        [
                            'key' => 'field_whx4_events_bymonth',
                            'label' => 'Months',
                            'name' => 'bymonth',
                            'type' => 'checkbox',
                            'choices' => [
                                '1' => 'January',
                                '2' => 'February',
                                '3' => 'March',
                                '4' => 'April',
                                '5' => 'May',
                                '6' => 'June',
                                '7' => 'July',
                                '8' => 'August',
                                '9' => 'September',
                                '10' => 'October',
                                '11' => 'November',
                                '12' => 'December',
                            ],
                            'conditional_logic' => [
                                [
                                    [
                                        'field' => 'field_whx4_events_freq',
                                        'operator' => '==',
                                        'value' => 'YEARLY',
                                    ]
                                ]
                            ],
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                        ],
                        [
                            'key' => 'field_whx4_events_count',
                            'label' => 'Number of occurrences',
                            'name' => 'count',
                            'type' => 'number',
                            'min' => 1,
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                        ],
                        [
                            'key' => 'field_whx4_events_until',
                            'label' => 'Repeat until',
                            'name' => 'until',
                            'type' => 'date_picker',
                            'display_format' => 'Y-m-d',
                            'return_format'  => 'Y-m-d',
                            'wrapper' => [
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ],
                        ],
                    ],
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_whx4_events_is_recurring',
                                'operator' => '==',
                                'value' => '1',
                            ]
                        ]
                    ],
                ],
                [
                    'key'           => 'field_whx4_events_excluded_dates',
                    'label'         => 'Excluded Dates (Read-only)',
                    'name'          => 'whx4_events_excluded_dates',
                    'type'          => 'textarea',
                    'instructions'  => 'Automatically updated from the instance list.',
                    'readonly'      => 1,
                    'rows'          => 3,
                    'wrapper'       => [
                        'width' => '40',
                    ],
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_whx4_events_is_recurring',
                                'operator' => '==',
                                'value' => '1',
                            ]
                        ]
                    ],
                ],
                [
                    'key'   => 'field_whx4_events_rrule',
                    'label' => 'Recurrence Rule',
                    'name'  => 'whx4_events_rrule',
                    'type'  => 'text',
                    'instructions' => 'iCal RRULE format (e.g. FREQ=WEEKLY;BYDAY=MO,WE)',
                    'required' => 0,
                    'readonly' => 1,
                    'wrapper' => [
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ],
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_whx4_events_is_recurring',
                                'operator' => '==',
                                'value' => '1',
                            ]
                        ]
                    ],
                ],
                // END recurrence rules WIP
                [
                    'key'   => 'field_whx4_events_legacy_em_event_id',
                    'label' => 'Legacy EM Event ID',
                    'name'  => 'whx4_events_legacy_em_event_id',
                    'type'  => 'number',
                    'readonly' => 1,
                    'wrapper' => [
                        'width' => '20',
                    ],
                ],
            ],
            'location' => [
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'event',
                    ],
                ],
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'whx4_event',
                    ],
                ]
            ],
        ]);

        // Copied from ATCHQ/Local
        acf_add_local_field_group( array(
            'key' => 'group_65f9fc95e1756',
            'title' => 'Event Details WIP',
            'fields' => array(
                array(
                    'key' => 'field_6628206cd24ec',
                    'label' => 'Date/Time/Location',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_65f9fc96b5e13',
                    'label' => 'Event Start Date',
                    'name' => 'event_start_date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_65fa00d44c9a8',
                    'label' => 'Event End Date',
                    'name' => 'event_end_date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_65fa01c385ac0',
                    'label' => 'Start Time',
                    'name' => 'event_start_time',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                array(
                    'key' => 'field_65fa01da85ac1',
                    'label' => 'End Time',
                    'name' => 'event_end_time',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                array(
                    'key' => 'field_65fa024f17d24',
                    'label' => 'Event Timezone',
                    'name' => 'event_timezone',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65fa0220c5816',
                    'label' => 'All Day Event',
                    'name' => 'event_all_day',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_66281ea405f6f',
                    'label' => 'Event Date/Time',
                    'name' => 'event_datetime',
                    'aria-label' => '',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'F j, Y H:i',
                    'return_format' => 'Y-m-d H:i',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_65fa029314e00',
                    'label' => 'Event Location',
                    'name' => 'event_location',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'venue',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'object',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_6620441923668',
                    'label' => 'Event Location TXT',
                    'name' => 'location_txt',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6620443023669',
                    'label' => 'Address TXT',
                    'name' => 'address_txt',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_66207668c8594',
                    'label' => 'Event Start Timestamp',
                    'name' => 'event_start_ts',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6620767fc8595',
                    'label' => 'Event End Timestamp',
                    'name' => 'event_end_ts',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6620424b9412f',
                    'label' => 'Event Start GMT',
                    'name' => 'event_start',
                    'aria-label' => '',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d H:i:s',
                    'return_format' => 'Y-m-d H:i:s',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_6620428194130',
                    'label' => 'Event End GMT',
                    'name' => 'event_end',
                    'aria-label' => '',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d H:i:s',
                    'return_format' => 'Y-m-d H:i:s',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_66282082d24ed',
                    'label' => 'iCal Data',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_65fa02c068d33',
                    'label' => 'Recurrence Info TMP',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => 'WIP -- vars may include (SEE wpstc_em_events):
            recurrence_id
            recurrence_interval
            recurrence_freq
            recurrence_byday
            recurrence_byweekno
            recurrence_days',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_6620488a6ad55',
                    'label' => 'Recurring Event',
                    'name' => 'recurring',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_662045209dfdf',
                    'label' => 'UID',
                    'name' => 'uid',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6620478ead203',
                    'label' => 'UUID',
                    'name' => 'uuid',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'iCal field',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_662047a6ad204',
                    'label' => 'Unique Identifier',
                    'name' => 'unique_identifier',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'iCal field',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_66204d1747350',
                    'label' => 'Event URL',
                    'name' => 'event_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'event',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) );
    }
}
