<?php

namespace atc\WHx4\Modules\Media\Fields;

use atc\WXC\Contracts\FieldGroupInterface;

final class MediaFields implements FieldGroupInterface
{
    public static function register(): void
    {
        if ( !function_exists('acf_add_local_field_group') ) return;

        acf_add_local_field_group( array(
			'key' => 'group_6644da528a729',
			'title' => 'Featured Audio/Video',
			'fields' => array(
				array(
					'key' => 'field_6644da529ead5',
					'label' => 'A/V Essentials',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_6644da529ea87',
					'label' => 'Show all fields',
					'name' => 'show_all_fields',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_6644da99f4f11',
					'label' => 'Featured A/V?',
					'name' => 'featured_AV',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => 'A post may have a video player and/or audio player. YouTube playlists are supported, but no more than one video or audio file may be featured per post.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'video' => 'Video',
						'audio' => 'Audio',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 0,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key' => 'field_6644da529eb6d',
					'label' => 'Media Format(s)',
					'name' => 'media_format',
					'aria-label' => '',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da99f4f11',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'youtube' => 'YouTube',
						'vimeo' => 'Vimeo',
						'video' => 'Video File',
						'audio' => 'Audio File',
					),
					'default_value' => array(
					),
					'return_format' => 'value',
					'allow_custom' => 0,
					'layout' => 'horizontal',
					'toggle' => 0,
					'save_custom' => 0,
					'custom_choice_button_text' => 'Add new choice',
				),
				array(
					'key' => 'field_6644da529ef38',
					'label' => 'Show CTA?',
					'name' => 'show_cta',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da99f4f11',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_664e5d3a0bc27',
					'label' => 'Webcast?',
					'name' => 'webcast',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da99f4f11',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_664e614ba88ea',
					'label' => 'Player Positioning',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da99f4f11',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'message' => 'You can choose whether the media player will be show above or below the page content. Selecting the "banner" option will position the player above the page header, immediately below the nav menu.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_664bba7e6332b',
					'label' => 'Video Player Position',
					'name' => 'video_player_position',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da99f4f11',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'above' => 'Above',
						'below' => 'Below',
						'banner' => 'Banner',
					),
					'default_value' => 'above',
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'horizontal',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_664bba8c6332c',
					'label' => 'Audio Player Position',
					'name' => 'audio_player_position',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => 'Generally only relevant for Sermon records',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da99f4f11',
								'operator' => '==',
								'value' => 'audio',
							),
						),
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'above' => 'Above',
						'below' => 'Below',
						'banner' => 'Banner',
					),
					'default_value' => 'below',
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'horizontal',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6644da529ebaa',
					'label' => 'Source',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_6644da529ec06',
					'label' => 'Video ID',
					'name' => 'video_id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'For Vimeo or YouTube',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'vimeo',
							),
						),
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'vimeo_recurring',
							),
						),
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'youtube',
							),
						),
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6644da529ecc5',
					'label' => 'YT Timestamp',
					'name' => 'yt_ts',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'Enter num. seconds (integer value)',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'youtube',
							),
						),
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6644da529ec48',
					'label' => 'YT Series ID',
					'name' => 'yt_series_id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'For YouTube playlist',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'youtube',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6644da529ec86',
					'label' => 'YT Playlist ID',
					'name' => 'yt_list_id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'For YouTube playlist',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'youtube',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_664baeeff3cf6',
					'label' => 'Video File',
					'name' => 'video_file',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'audio',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4, mov',
				),
				array(
					'key' => 'field_664baf00f3cf7',
					'label' => 'Video File -- Mobile Version',
					'name' => 'video_file_mobile',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'video',
							),
						),
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'audio',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4, mov',
				),
				array(
					'key' => 'field_6644da529ed84',
					'label' => 'Audio File',
					'name' => 'audio_file',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529eb6d',
								'operator' => '==',
								'value' => 'audio',
							),
						),
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'wav, mp3, m4a',
				),
				array(
					'key' => 'field_6644da529edc4',
					'label' => 'Cue Points',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_6644da529ee21',
					'label' => 'Cue Points',
					'name' => 'cuepoints',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6644da52e21de',
							'label' => 'Program Label',
							'name' => 'item_label',
							'aria-label' => '',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'program_label',
							),
							'taxonomy' => '',
							'filters' => array(
								0 => 'search',
							),
							'elements' => '',
							'min' => '',
							'max' => '',
							'return_format' => 'object',
							'bidirectional_target' => array(
							),
							'parent_repeater' => 'field_6644da529ee21',
						),
						array(
							'key' => 'field_6644da52e224d',
							'label' => 'Name',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'parent_repeater' => 'field_6644da529ee21',
						),
						array(
							'key' => 'field_6644da52e2293',
							'label' => 'Start Time',
							'name' => 'start_time',
							'aria-label' => '',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'H:i:s',
							'return_format' => 'H:i:s',
							'parent_repeater' => 'field_6644da529ee21',
						),
						array(
							'key' => 'field_6644da52e22d4',
							'label' => 'End Time',
							'name' => 'end_time',
							'aria-label' => '',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'H:i:s',
							'return_format' => 'H:i:s',
							'parent_repeater' => 'field_6644da529ee21',
						),
					),
				),
				array(
					'key' => 'field_6644da529ee5f',
					'label' => 'Webcast Details',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
						array(
							array(
								'field' => 'field_664e5d3a0bc27',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'placement' => 'top',
					'endpoint' => 0,
					'selected' => 0,
				),
				array(
					'key' => 'field_6644da529eb29',
					'label' => 'Webcast Status',
					'name' => 'webcast_status',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'choices' => array(
						'before' => 'Before',
						'live' => 'Live',
						'after' => 'After',
						'on_demand' => 'On Demand',
						'technical_difficulties' => 'Technical Difficulties',
						'cancelled' => 'Cancelled',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6644da529ed04',
					'label' => 'Live URL',
					'name' => 'url_live',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_6644da529ed42',
					'label' => 'On-Demand URL',
					'name' => 'url_ondemand',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6644da529ea87',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'relevanssi_exclude' => 0,
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_6644da529efe3',
					'label' => 'Webcast Notes',
					'name' => 'webcast_notes',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'event',
					),
				),
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'event-recurring',
					),
				),
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'page',
					),
				),
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
					),
				),
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'sermon',
					),
				),
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'person', // TBD: what happens if WHx4 plugin is not installed with People module active?
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'field',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
		) );
    }
}
